// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdsyOzEHJSxK2JsLXA_FC0HdyrwtMoWEY',
    appId: '1:510080118983:web:136b92f4178fb3b71e8ee2',
    messagingSenderId: '510080118983',
    projectId: 'issuereporter-102bd',
    authDomain: 'issuereporter-102bd.firebaseapp.com',
    storageBucket: 'issuereporter-102bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwvhUS7EgUAJeSuXZ_kYyYfgIg-YTAOs4',
    appId: '1:510080118983:android:ab9d7f5b33b1ff1c1e8ee2',
    messagingSenderId: '510080118983',
    projectId: 'issuereporter-102bd',
    storageBucket: 'issuereporter-102bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9z4V5llNEqbwHTwUDwaR3Sbus3mGg5dU',
    appId: '1:510080118983:ios:56573ec26d16f0ef1e8ee2',
    messagingSenderId: '510080118983',
    projectId: 'issuereporter-102bd',
    storageBucket: 'issuereporter-102bd.appspot.com',
    iosBundleId: 'com.example.reportIssue',
  );
}
